services:
  postgres:
    image: postgres:16
    container_name: pacs-postgres
    environment:
      POSTGRES_USER: pacs_user
      POSTGRES_PASSWORD: pacs_password
      POSTGRES_DB: pacs_database
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data:
